power<-data.table(read.csv("cleaned.csv"))
png("plot1.png",width=480,height = 480,units="px")
colnames(power)
hist(power$Globalactivepower,col="red",xlab = "Global Active Power (kilowatts)")
x<-dev.off()
